# uosc provides seeking & volume indicators (via flash-timeline and flash-volume commands)
# if you decide to use them, you don't need osd-bar
osd-bar=no

# uosc will draw its own window controls and border if you disable window border
border=no

# 设置字体为霞鹜文楷等宽字体 (LXGW WenKai Mono)
# 字体文件已放在 portable_config/fonts/ 目录下
# 也可以尝试以下备选字体名，如果上面的不工作：
# osd-font=LXGWWenKaiMono
#osd-font= Microsoft YaHei
osd-font=LXGW WenKai Mono

# log-file=mpv.log
msg-level=all=info,epg=trace
msg-level=ffmpeg=no

 ## AMD核显最优解码
gpu-context=d3d11
hwdec=auto
hwdec-codecs=all
temporal-dither=yes

# --- 渲染优化 ---
# profile=high-quality           # 使用高质量预设,集成显卡不要使用
vo=gpu-next                   # 使用新的GPU渲染器，提供更好的性能和质量

# # 缓存 #
demuxer-max-bytes = 1024MiB

## 窗口秒开
force-window=immediate
idle=yes

## 固定1080P窗口和位置
autofit=1920x1080
geometry=1920x1080+1920-1040

## 25帧 IPTV 补帧到 60Hz 顺滑  好像效果不大,按i 显示estmate 59.5 fps
interpolation=yes
tscale=oversample
video-sync=display-resample
blend-subtitles=yes
video-sync-max-video-change=10

playlist-start=1000
prefetch-playlist=yes

# #IPTV配置
# # 或者伪装成常见的智能电视/机顶盒 (某些特定的 IPTV 源可能需要)
user-agent=SYTV/1.6
# # 2. 忽略 SSL 证书错误
# # 很多个人维护或小型的 IPTV 源 HTTPS 证书是过期或无效的
# tls-verify=no
# # 达到多少秒的缓存后才开始播放 (对于卡顿的源，可以设置为 2-3 秒)
# # cache-secs=2 
# # 4. 底层断线自动重连 (对抗不稳定源的神器)
# # 传递给底层的 ffmpeg (libavformat)，让它在网络断开或超时时自动重试
# demuxer-lavf-o=reconnect=1,reconnect_at_eof=1,reconnect_streamed=1,reconnect_delay_max=5
# # 5. 超时与网络相关
# network-timeout=10          # 连接超时时间（秒）
# stream-buffer-size=4m       # 加大流缓冲区
# # 6. 丢帧与音视频同步 (针对直播流)
# # 如果网络卡顿导致音视频不同步，优先保证音频继续播放，视频可以丢帧赶上
# framedrop=decoder+vo